[package]
name = "gmanim-python-binding"
version = "0.1.0"
edition = "2024"

[lib]
name = "gmanim"
crate-type = ["cdylib", "rlib"]

[dependencies]
gmanim_core = { package = "gmanim-core", path = "../gmanim" }
gmanim-editor-protocol = { path = "../gmanim-editor/protocol" }
pyo3 = { version = "0.28" }
nalgebra = "0.35"
indicatif = "0.17"
shared_memory = "0.12.4"
interprocess = "2.4.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]
