from typing import Optional

# Extension-module exports (must match src/lib.rs m.add_class order/names).
from .gmanim import (
    Scene,
    PreviewSession,
    SceneFrame,
    Mobject,
    Line,
    Rectangle,
    PolyLine,
    Arc,
    QuadraticBezier,
    Dot,
    Text,
    Sphere3D,
    LineSegment3D,
    QuadraticBezier3D,
    Arrow3D,
    Box3D,
    Box3DSdf,
    Mesh2DIn3D,
    TriangleMesh3D,
    Cylinder3D,
    Cone3D,
    Group,
    Animation,
    Move,
    Rotate,
    Wait,
    PyVideoBackend,
    H264RateControl,
    VulkanH264Config,
)

# Pure-Python package exports.
from .animations import UpdateFromFunc
from .mobjects import (
    Axes3D,
    Axes3DRound,
    Line2DMesh3D,
    Arc2DMesh3D,
    Rectangle2DMesh3D,
    PolyLine2DMesh3D,
    Text2DMesh3D,
)
from .types import Color, Point2, Point3

__all__ = [
    "Scene",
    "PreviewSession",
    "SceneFrame",
    "Mobject",
    "Line",
    "Rectangle",
    "PolyLine",
    "Arc",
    "QuadraticBezier",
    "Dot",
    "Text",
    "Sphere3D",
    "LineSegment3D",
    "QuadraticBezier3D",
    "Arrow3D",
    "Box3D",
    "Box3DSdf",
    "Mesh2DIn3D",
    "TriangleMesh3D",
    "Cylinder3D",
    "Cone3D",
    "Group",
    "Animation",
    "Move",
    "Rotate",
    "Wait",
    "UpdateFromFunc",
    "PyVideoBackend",
    "H264RateControl",
    "VulkanH264Config",
    "Color",
    "Point2",
    "Point3",
    "Axes3D",
    "Axes3DRound",
    "Line2DMesh3D",
    "Arc2DMesh3D",
    "Rectangle2DMesh3D",
    "PolyLine2DMesh3D",
    "Text2DMesh3D",
]
__doc__: Optional[str]
